server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web-socket
    username: postgres
    password: root123
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  sql:
    init:
      mode: never


logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: /logs/online_shop.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
